### ISSUE TITLE
チャットコマンド&sで返ってくるシナリオのファイル名が常にSystem.rcsになる

### ISSUE THREAD

**Issue by FSenbei** [rigidchips-lib/rigidchips#17]
ファイル名に続いて書かれているシナリオコードは機能しているらしい？

**Comment by siruhu** [comment]
Rigidmain.cpp 5557行目 _tcscpy( CurrScenarioDir, CurrDataDir ); の前に
            lstrcpy(szSystemFileName0,szTitle);
            lstrcat(szSystemFileName0,szExt);
を追加で正常動作確認
手前でﾌｧｲﾙﾈｰﾑの切り出しまでやってくれてるし、OpenLandとかもこの流れで書いてるんでこっちの場所のがいいんじゃないかな
