### ISSUE TITLE
透明化のバグ

### ISSUE THREAD

**Issue by tanitta** [rigidchips-lib/rigidchips#2]
ネットワーク接続時にpauseを解くと自分のモデルが他のプレイヤーから表示されなくなる場合がある．

**Comment by poruru** [comment]
透明化のバグ状態のプレイヤーはマーカだけ見える．
CCDがOFFの場合，マーカは停止して見える．
CCDをONにすると透明のままだがマーカが本来の位置を示す．
CCDの視界では透明化したプレイヤーも正常に表示される．

**Comment by siruhu** [comment]
PauseｵﾝｵﾌよりPlayer接続切断時に発生してる気がする
透明化したﾌﾟﾚｲﾔｰ番号(名前ﾘｽﾄの位置)は接続切断によって席がずれた場合、対象の番号に当たった人が消える
対象の番号から外れた人は出現する
末尾から消えてく   ･･･気がする

**Comment by siruhu** [comment]
これ、Jet大量についたﾓﾃﾞﾙ出してからJet少ないﾓﾃﾞﾙ出したら鬼火発生しない?
した。確定
Jet吹かした状態でﾓﾃﾞﾙ変更で鬼火発生
出力0のJet*511ﾓﾃﾞﾙ読み込んでから他のﾓﾃﾞﾙ読んで鬼火消滅

**Comment by siruhu** [comment]
これ配列初期化してないRigidmain.cpp 2342行めでPlayerData[n].Jet[PlayerData[n].ChipCount]=0;してるんだけど、これより手前でcontinue掛かるとﾘｾｯﾄされない
そして、2498行目のJet描画判定でif(PlayerData[i].Jet[j]>0) {使ってる

**Comment by wakarikaneru** [comment]
厳密には確認してないけど
ローカルで複数立ち上げた時にも発生する気がする
その時には一旦、見えてる人数が少なくなっている方(透明になっていない方)のクライアントをRCで接続し直すと改善するって事が何回かあった

**Comment by ray45422** [comment]
Slackを見たところ
CCDの描画っぽいとこではfor(i=0;i<DPlay->GetNumPlayers();i++) { World->DispNetChip(i); }
ﾒｲﾝっぽいとこではfor(i=0;i<(unsigned int)DPlay->GetCurrentPlayers();i++) { World->DispNetChip(i); }
になってるらしいのでRigidMain.cpp:6918のGetCurrentPlayers()をGetNumPlayers()に書き換えるだけで治る模様

**Comment by tanitta** [comment]
該当行です．
- CCD
  https://github.com/rigidchips-lib/rigidchips/blob/dev/src%2FRigidmain.cpp#L7245
- メイン描画
  https://github.com/rigidchips-lib/rigidchips/blob/dev/src%2FRigidmain.cpp#L6791
