### ISSUE TITLE
ウィンドウ最大化による非ドットバイドット表示

### ISSUE THREAD

**Issue by oliwehr-sds** [rigidchips-lib/rigidchips#28]
ウィンドウを最大化する方法には、最大化ボタンを押す方法と、タイトルバーをダブルクリックする方法の2通りが存在する。最大化ボタンを押す場合には、解像度がウィンドウ描画領域に合わせて更新され、ドットバイドットになる。一方、タイトルバーをダブルクリックする場合には、解像度が更新されず、直前の解像度のまま描画された画像が引き伸ばされて表示される。

**Comment by sabatotan** [comment]
原因として、
d3dapp.cppに、ウィンドウサイズが変わった際にD3D周りのサイズも同時に変更するコードが有るところ、
WM_SYSCOMMAND→SC_MAXMIZE（最大化ボタンを押した場合）
WM_EXITSIZEMOVE（ウィンドウをドラッグで移動・拡大縮小した場合）
にのみ該当コードがあり、タイトルバーをダブルクリックした場合について処理していないことがあげられる。

**Comment by sabatotan** [comment]
但し、タイトルバーダブルクリックのメッセージ（WM_NCLBUTTONDBLCLK && wParam==HTCAPTION）を受信した段階では、「最大化後の画面サイズ」がわからないため、このメッセージを処理してD3Dの画面サイズを変更する方法がない。どうしたものか

**Comment by sabatotan** [comment]
以下のコードを
d3dapp.cpp line:629の後に挿入すると治る

case WM_NCLBUTTONDBLCLK:
			if (wParam == HTCAPTION)
			{
				if (IsZoomed(hWnd))
				{
					SendMessage(hWnd, WM_SYSCOMMAND, SC_RESTORE, 0);
				}
				else
				{
					SendMessage(hWnd, WM_SYSCOMMAND, SC_MAXIMIZE, 0);
				}
			}
			return S_OK;
