### ISSUE TITLE
鬼火バグ

### ISSUE THREAD

**Issue by poruru** [rigidchips-lib/rigidchips#4]
Jetが無い所にJet噴射炎が表示されるバグ．
透明カウルが多い所に観測される気がする．
透明化したプレイヤーにも鬼火は発生する．

**Comment by poruru** [comment]
鬼火はマーカに追従する．
透明化したプレイヤーの鬼火は，CCDがOFFのの時はマーカと共に停止し，ONの時はマーカと共に動く．

**Comment by poruru** [comment]
カウル表示ONOFFは関係なく発生する．
RegulationのJetOFFによって消える．

**Comment by siruhu** [comment]
これ、Jet大量についたﾓﾃﾞﾙ出してからJet少ないﾓﾃﾞﾙ出したら鬼火発生しない?
した。確定
Jet吹かした状態でﾓﾃﾞﾙ変更で鬼火発生
出力0のJet*511ﾓﾃﾞﾙ読み込んでから他のﾓﾃﾞﾙ読んで鬼火消滅

**Comment by siruhu** [comment]
これ配列初期化してないRigidmain.cpp 2342行めでPlayerData[n].Jet[PlayerData[n].ChipCount]=0;してるんだけど、これより手前でcontinue掛かるとﾘｾｯﾄされない
そして、2498行目のJet描画判定でif(PlayerData[i].Jet[j]>0) {使ってる

**Comment by siruhu** [comment]
2342行目のPlayerData[n].Jet[PlayerData[n].ChipCount]=0;を切り取り、2183行目の前に移植だけで解消した
