### ISSUE TITLE
ﾎｲｰﾙﾊﾞｸﾞ継続(ﾎﾞｰﾙとの接触のみ)

### ISSUE THREAD

**Issue by siruhu** [rigidchips-lib/rigidchips#72]
GRigid.cpp 1018行目の分岐、ぶつかった先が地面以外の場合(つまり現状はﾎﾞｰﾙとの接触のみ)はぶつかった相手のUd,Us取ってるが、Uxだけ常に自身のUxを使ってるためﾎｲｰﾙﾊﾞｸﾞが残ってる

**Comment by siruhu** [comment]
Grigid.cpp 916行目 GRigid::Impulse()関数内のHit[i].Ux;をuxに置換
1017行目 GFloat ud;の次にGFloat ux;の定義を追加
1018行目 if(Hit[i].Target->Type==-1) {の条件式内 ud=Ud_Hit[i].Ud_uk;の次にux=Hit[i].Ux;
ud=Ud_Hit[i].Target->Ud_uk;の次に ux=Hit[i].Target->Ux;を追記
1010行目 //ころがり摩擦    から下4行 } までを切り取り   1018行目からのif(Hit[i].Target->Type==-1)を閉じた後ろに挿入

これでおそらくﾎｲｰﾙﾊﾞｸﾞ系は完治じゃないかな･･･

**Comment by lempiji** [comment]
#115 にて修正済み
