### ISSUE TITLE
ホイールバグ

### ISSUE THREAD

**Issue by tanitta** [rigidchips-lib/rigidchips#8]
ホイールがLandのFaceと接触する際に激しく挙動が乱れる場合がある

**Comment by wakarikaneru** [comment]
ホイールバグ発生時にホイールの出力が無限大になっている気がする

**Comment by siruhu** [comment]
出力無限大じゃなくてｾﾞﾛ除算結果じゃないっけあれ
あと砂煙ﾊﾞｸﾞもここでいいよね

**Comment by siruhu** [comment]
Hit[n]に関してすごく雑に調査した所多くても要素数20に満たなかった
GRigid.cpp 938行目  //if(HitN>32) hn=32;  でHitNについて32までのﾘﾐｯﾀがｺﾒﾝﾄｱｳﾄされてるのもあるし、配列長100もあれば問題なさそう
そもそも単純な配列長ｵｰﾊﾞｰなら地面にﾎｲｰﾙ大量にぶちまけたらすぐ再現できそうだよね

**Comment by siruhu** [comment]
rally_ssﾏｯﾌﾟの森っぽい壁にぶつかることでﾎｲｰﾙﾊﾞｸﾞがほぼ再現   その後柵に当てる(複数枚のﾎﾟﾘに同時接触?)で解消される模様

**Comment by siruhu** [comment]
GRigid.cpp 724行目から  UsとUdしか更新されてない  Uxが未初期化が原因で確定っぽい
とりあえずUx=0を書き足したら症状が出なくなった

**Comment by siruhu** [comment]
この周辺、15B10で転がり抵抗追加した時にUxについての追加をまるごと忘れたっぽい
GLand.hpp371行目からのGLand::Check()もUxに未対応なんで
371行目GFloat Check(const GVector &p,const GVector &v,GVector &n,GFloat &Ud,GFloat &Us) {
 >> GFloat Check(const GVector &p,const GVector &v,GVector &n,GFloat &Ud,GFloat &Us,GFloat &Ux) {
381行目の次に Ux=Face[List1[i]].Ux;を追加して、GRigid.cppのGLand::Check()の呼び出しを全部いじればよさそう?

**Comment by siruhu** [comment]
今までと変わらない挙動って意味ではUx未初期化(多分大体0)で変化してなかった気もするので、各分岐でHit[HitN].Us=us;の次にHit[HitN].Ux=0.0f;を書き足すだけのほうがいいかも

**Comment by tanitta** [comment]
PRで解決したのでcloseします
